version: 2

run:
  timeout: 3m

linters:
  enable:
    - errcheck    # Vérifie si les erreurs sont bien gérées
    - govet       # Détecte les erreurs suspectes
    - ineffassign # Détecte les assignations inutiles
    - staticcheck # Analyse statique poussée
    - unused      # Détecte le code mort / non utilisé

issues:
  exclude-use-default: false