services:
  traefik:
    image: traefik:v3.6
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8082:8082"
    healthcheck:
      test: ["CMD-SHELL", "traefik healthcheck --ping"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ../traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ../traefik/dynamic/dynamic.yml:/etc/traefik/dynamic.yml:ro
      - ../traefik/certs:/etc/traefik/certs:ro
      - ../traefik/.htpasswd:/etc/traefik/htpasswd:ro
    networks:
      - frontend_network

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile.prod
    restart: always
    environment:
      ENV: production
      BACKEND_PORT: ${BACKEND_PORT}
      DATABASE_URL: "postgres://${DB_USER}:${DB_PASSWORD}@database:5432/${DB_NAME}?sslmode=disable"
      JWT_SECRET: ${JWT_SECRET}
      LOG_LEVEL: ${LOG_LEVEL}
    depends_on:
      database:
        condition: service_healthy
    networks:
      - backend_network
      - frontend_network

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile.prod
      args:
        API_URL: ${API_URL}
    restart: always
    networks:
      - frontend_network

  database:
    image: postgres:17.2-alpine
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - backend_network
    volumes:
      - database_data:/var/lib/postgresql/data
      - ../db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

networks:
  backend_network:
    driver: bridge
  frontend_network:
    driver: bridge

volumes:
  database_data: