-- 1. Création des types ENUM (Conforme au cahier des charges [1, 2])
CREATE TYPE "role" AS ENUM ('admin', 'tech', 'standard');
CREATE TYPE "status" AS ENUM ('open', 'in_progress', 'resolved', 'closed');
CREATE TYPE "priority" AS ENUM ('low', 'mid', 'high', 'critical');

-- 2. Table Utilisateurs
CREATE TABLE IF NOT EXISTS "users" (
    "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    "firstname" VARCHAR(255),
    "lastname" VARCHAR(255),
    "email" VARCHAR(255) UNIQUE NOT NULL,
    "password_hash" VARCHAR(255) NOT NULL,
    "role" "role" NOT NULL DEFAULT 'standard',
    "created_at" TIMESTAMPTZ DEFAULT NOW(),
    "updated_at" TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Table Catégories
CREATE TABLE IF NOT EXISTS "categories" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL
);

-- 4. Table Tickets (Inclut resolved_at pour les métriques [2, 3])
CREATE TABLE IF NOT EXISTS "tickets" (
    "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    "title" VARCHAR(255) NOT NULL,
    "description" TEXT,
    "status" "status" NOT NULL DEFAULT 'open',
    "priority" "priority" NOT NULL DEFAULT 'low',
    "category_id" INTEGER,
    "created_by" UUID,
    "assigned_to" UUID,
    "created_at" TIMESTAMPTZ DEFAULT NOW(),
    "updated_at" TIMESTAMPTZ DEFAULT NOW(),
    "resolved_at" TIMESTAMPTZ -- Important pour calculer le "Temps moyen de résolution" [2, 3]
);

-- 5. Table Historique d'assignation
CREATE TABLE IF NOT EXISTS "ticket_assignment_history" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ticket_id" UUID NOT NULL,
    "assigned_to_user_id" UUID,
    "assigned_by_user_id" UUID,
    "assigned_at" TIMESTAMPTZ DEFAULT NOW(),
    "ended_at" TIMESTAMPTZ,
    "status_at_assignment" "status"
);

-- 6. Table Refresh Tokens (Sécurité)
CREATE TABLE IF NOT EXISTS "refresh_token" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" UUID NOT NULL,
    "token_hash" TEXT NOT NULL,
    "revoked" BOOLEAN DEFAULT FALSE,
    "expires_at" TIMESTAMPTZ NOT NULL,
    "created_at" TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Définition des contraintes et comportement au DELETE

-- Pour les tickets : on garde le ticket même si l'user est supprimé (pour les stats)
ALTER TABLE "tickets"
ADD FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE SET NULL,
ADD FOREIGN KEY ("assigned_to") REFERENCES "users"("id") ON DELETE SET NULL,
ADD FOREIGN KEY ("category_id") REFERENCES "categories"("id") ON DELETE SET NULL;

-- Pour l'historique : on supprime l'historique si le ticket est supprimé (CASCADE)
-- Mais on garde la trace de l'action si l'user est supprimé (SET NULL)
ALTER TABLE "ticket_assignment_history"
ADD FOREIGN KEY ("ticket_id") REFERENCES "tickets"("id") ON DELETE CASCADE,
ADD FOREIGN KEY ("assigned_to_user_id") REFERENCES "users"("id") ON DELETE SET NULL,
ADD FOREIGN KEY ("assigned_by_user_id") REFERENCES "users"("id") ON DELETE SET NULL;

-- Pour la sécurité : si l'user disparaît, ses accès disparaissent
ALTER TABLE "refresh_token"
ADD FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE;